version: '3'
networks:
    laravel:
        driver: bridge
services:
    nginx:
        image: nginx:alpine
        tty: true
        ports:
            - "8086:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - laravel
    app:
        build: docker/app
        volumes:
            - ./:/var/www/:cached
        working_dir: /var/www/src
        environment:
            APP_URL: http://localhost
            MIX_APP_URL_API: http://localhost/api
        depends_on:
            - db
        networks:
            - laravel
    db:
        platform: linux/x86_64
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: crawler_db
            MYSQL_USER: crawler
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql/db-data:/var/lib/mysql:cached
            - ./docker/mysql/mysql_confd:/etc/mysql/conf.d:cached
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "phpmyadmin_crawler"
        ports:
          - "8080:80"
        volumes:
          - /sessions
        depends_on:
          - db
        networks:
            - laravel
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8065:8025"
        networks:
            - laravel
volumes:
    db-data:
